### ISSUE TITLE
Can't open the debug menu

### ISSUE THREAD

**Issue by extails19** [seanpr96/DebugMod#3]
May I ask which is the Keybind of the debug menu?

**Comment by Nippius** [comment]
From the steam community forums it was supposed to be "backspace" but it isn't working for me either... (v 1.3.1.5)

**Comment by seresharp** [comment]
It's F1

**Comment by Nippius** [comment]
Thank you. I found it in the code today anyway but it doesn't work either :/ Is there anything else I can try? I don't think that I have anything else that could interfere with it.

**Comment by seresharp** [comment]
You probably did not install the mod correctly. I can help you much faster if we talk in the #modding-help channel here http://discord.gg/hollowknight

**Comment by seresharp** [comment]
Issue solved on discord server, user had not installed the mod properly.
